### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#352]
- [x] Release 0.19
- [x] Get all the League extensions to a good point (including 0.19 support)
- [x] Finalize AST decision (see #232)
- [x] Refactor delimiter processing, maybe using the Java lib as an example (see #357)
- [x] Expand delimiter functionality to allow delims with different open/closing characters (see #363)
- [x] ~Consider whether to implement event dispatcher support now (see #359)~ waiting until 2.0
- [x] Address ISO-8859-1 support (see #361)
- [x] Do a final review of the codebase for legacy things that we may want to deprecate, remove, refactor, `final`ize, etc. (#360)
- [x] Figure out whether the spec plans to release any updates soon
- [x] ~Remove~ Undeprecate the `CommonMarkConverter::VERSION` constant - **we're going to keep it**

**Comment by markcarver** [comment]
This project really needs to follow semver.

The way semver/composer handles <1.0.0 versions is... odd.

Introducing breaking changes in minor releases causes things like https://www.drupal.org/project/markdown/issues/3048976



> * [ ]  Remove the `CommonMarkConverter::VERSION` constant

Why? This is still needed.

**Comment by markcarver** [comment]
Also, removing PHP 5.6 and 7.0 support should have happened in 1.0.0, not a minor release. As it stands now, I think we'll be locked into only being able to support 0.18.3.

**Comment by colinodell** [comment]
>

We do follow [SemVer](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

[We actually take this a step further](https://github.com/thephpleague/commonmark#versioning) by treating `0.x` as major versions and `0.x.y` as minor ones (instead of breaking anything at any time).

> As it stands now, I think we'll be locked into only being able to support 0.18.3 as Drupal core still supports older versions of PHP (including the 7.x branch, which the module will need to support).

Not necessarily.  You can set a wider constraint which includes both `0.18.x` and `0.19.x` (or even higher).  Composer will automatically select the highest version which is compatible with that user's PHP version.  If they're on PHP 5.6 they'll get `0.18.x`, otherwise they'll get a newer version.

The breaking change in that Drupal.org issue is due to the custom functionality that's bundled into that project.  The constraints in that module currently say it's compatible with ALL future versions of `league/commonmark`, including `0.19`, `1.x`, and any/all future versions.  We strongly recommend not using that type of constraint for exactly this reason - we can't promise to never break BC in future major version (whether that's a >=1.0 major version or an 0.x major version).

That being said, it should still be possible to support both `0.18.x` and `0.19.x`.  You could create two different versions of those parsers/renderers/extensions and then leverage something like the `CommonMarkConverter::VERSION` constant to figure out which version to include.   For example:

```php
if (strpos(CommonMarkConverter::VERSION, "0.19") === 0) {
  $environment->addExtension(new CommonMark019Extension());
} elseif (strpos(CommonMarkConverter::VERSION, "0.18") === 0) {
  $environment->addExtension(new CommonMark018Extension());
}
```

```php
class CommonMark018Extension extends Extension
{
  // TODO: Use the older version of Extension with multiple methods, one per each parser/renderer/etc type
  // ...
}
```

```php
class CommonMark019Extension implements ExtensionInterface
{
  // TODO: Use the newer ExtensionInterface which now has a single method
  // ...
}
```

It should definitely be doable, but I completely understand that maintaining multiple versions of the "same" functionality is a hassle for maintainers like yourself.  **This is why I want to get to 1.0 as quickly as possible.**  Thankfully we are **very close** - there are only one or two more potential BC-breaks that I envision us making before then:

 - Refactoring the delimiter processing (via #357 - currently pending some more testing)
 - Deciding whether or not to tackle #232 (though I'm thinking the current implementation is good enough for now and we should focus on that in v2 instead)

I don't want to make any promises right now, but 1.0 _could_ come as early as next month!

> > Remove the `CommonMarkConverter::VERSION` constant
>
> Why? This is still needed.

Because it's a minor pain to keep it updated and I honestly forgot that you had requested this in #314.

Let me ask this - if I keep this constant in all future 0.x and 1.x releases, would you consider using it to help you overcome the BC breaks?  I think that could be a win-win for both of our projects - yes, it does increase maintenance overhead, but it would continue to make it possible for newer versions to be supported.

Let me know your thoughts!

**Comment by markcarver** [comment]
> This project really needs to follow semver.

Sorry, didn't really mean to say it this way. I'm just frustrated is all (mostly with semver/composer). Take what I have here with a grain of salt... it's more of me just venting/thinking out loud (please don't take it personally as I don't mean it that way).

What I had meant to say is that this project really needs to get out of the "initial development" versions as semver calls it.

> The 50th release of `league/commonmark` is here! 🎉 - [0.19.0](https://github.com/thephpleague/commonmark/releases/tag/0.19.0)

It's a little telling that there have been 50+ releases and it's still using "initial development" versioning... clearly, it's not "initial" anymore especially considering that it's been going on for 5+ years. There really should have already been several [normal] major version bumps by now.

The way semver/composer handles these versions is what's odd, not that this project is using it incorrectly. I have never liked the 0.x versions (same for nodejs) as they are used inconsistently by package managers and developers alike.

Typical caret and tilde constraints mean different things when using the "initial development" version and we run into issues like the above.

IMO, this is the one major fallacy of semver: changing the meaning for versions lower than 1.0.0 to use a special "initial development" semver meaning. It's stupid (on semver's part, not this project's or you).

> We strongly recommend not using that type of constraint for exactly this reason

Except that this type of constraint (when using normal semver) is what would allow module releases to technically live a little longer and require less maintenance on my part. This is what I mean by "it needs to follow semver". The "initial development, while semver, really isn't semver when it's treated differently by package managers such as composer, https://getcomposer.org/doc/articles/versions.md#caret-version-range-:

> The `^` operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example `^1.2.3` is equivalent to `>=1.2.3 <2.0.0` as none of the releases until `2.0` should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.

This means that each `0.x` (which semver and you are calling major) does not coincide with the rest of semver (>=1.0.0) where `x` is really a minor version, not major. Thus, each time a new "major" is released, the module has to be manually updated... thus, nullifying the whole point of attempting to use `^` in the first place (which really only works well with real semver).

> we can't promise to never break BC in future major version (whether that's a >=1.0 major version or an 0.x major version).

Um... why not? Isn't that the whole point of using semver in the first place? If you have to break BC, then it's time for a major version bump; plain and simple. I really don't get the aversion to bumping majors when it's appropriate to do so. So what if the version number is `31.2.343`. Is it "pretty", no... but it is safe. I mean, I suppose that's why there's now a `0.19` "major"... but that really should have been something like `3.0.0` or `19.0.0` or whatever...

> Composer will automatically select the highest version which is compatible with that user's PHP version.

In theory, yes... it _should_ work this way. In practice, it doesn't always do this... especially when a complex ecosystem like Drupal is involved and especially when "initial development" versions are involved because their constraint is treated differently than normal semver constraints.

I was just saying that it seemed a bit shortsighted to implement this change in a pre-1.0 release, thus requiring all PHP 5.6 implementations a hard stop at `0.18.3` (which didn't even, technically, get to a "stable" 1.0.0 release).

> You could create two different versions of those parsers/renderers/extensions and then leverage something like the `CommonMarkConverter::VERSION` constant to figure out which version to include.

Yes... I _could_ do that... or we could simply follow proper semver which is supposed to imply that new majors are not BC. I mean, I'll likely have to do this anyway given how literally almost every "major" version since `0.15` has had some change or another. The alternative is to wait for a proper 1.0.0 release I guess and just avoid this whole headache in the first place.

I think, though, one of the primary issues is how this project handles adding new features and then immediately removes the code it's intended to replace.

Take for example #357, the PR is essentially ripping out all the "inline processing" APIs and replacing it with a new "delimiter processing" API... in the same PR. There is absolutely no breathing room here. This is what constitutes a BC break and why it would require a new major bump.

Instead, this is where the "inline processing" code should just **deprecated** and the new feature is added in a **minor** release. Then all subsequent core code/extensions are updated in a similar fashion to use the newly added APIs. There's no need to have a major release each time something changes like this. There can be a little bit of overlap.

Yes, leaving in old code adds "technical debt", but it also allows for a little bit of code stability. This is where a release schedule might help with determining how to implement new features while deprecating old ones. Over time, as new majors are released, deprecated code can be removed as needed, safely.

If releases are constantly being pumped out that break BC, then by the time someone has a chance to develop against the current implementation... it changes and is gone as soon as they "update". Heaven forbid if there's a security update... now all the APIs/code has to be updated to utilize the new APIs of the major release just so the security issue can be attended to (patching isn't always viable if there hasn't been stability in the project between releases, e.g. more major releases than minor or patches).

This is what has made developing extensions extremely difficult in the past. As soon as a new 0.x version was out, the extension almost inevitably stopped working or wouldn't install due to composer "initial development" constraints (because it isn't "real" semver).

IMO, #232 is a "future task" issue. Regardless if it's a`2.0.0` or even a `3.0.0` version bump... when it's ready, whatever the next major version is... it bumps up to in that. There's no need to block 1.0.0 or any current major milestone on it now if it still needs time to be thought out and developed properly.

> if I keep this constant in all future 0.x and 1.x releases, would you consider using it to help you overcome the BC breaks?

As it stands now, it'll likely just be used to determine the current version installed more than anything. As time goes on and new features/settings are added, then I suspect it will be used more and more (e.g. 1.1.0 adds a new setting, then 1.2.0 adds a new setting and we have to determine what to show in the UI).

Supporting different extension classes will likely not be the initial goal of using this constant though, that should really be left to semver (as that is its entire purpose). This is why I want to get to `1.0.0` because then I can just rely on this and not have to worry that any minor or patch release is going to break existing APIs.

Regardless, this constant is necessary for the various reasons I pointed out in #314, primarily due to performance reasons and Drupal limitations.

Perhaps in the future, when `2.0.0` rolls around and I need to support both, then yes... there may come a time when it's used for this, likely as multiple extensions in versioned namespaces.

> I don't want to make any promises right now, but 1.0 _could_ come as early as next month!

I think `1.0.0` has been ready for a while, probably even what `0.19.0` should have been...

---

Summary:

- I think getting out of the "initial development" versioning is the most important step forward.
- I think the two issues mentioned (#357) and (#232) are really not hard blockers for a `1.0.0` release.
- I think that new features that replace the functionality of existing code should instead deprecated existing code rather than remove it entirely, thus allowing for more minor releases opposed to only major ones.
- I think the version constant is still needed, regardless of how I'm using it... there may be reasons why other people are using it; it's just necessary. Perhaps some commenting needs to be added around why it's necessary (extracted from some of my reasons in #314).

**Comment by colinodell** [comment]
Thank you for the detailed feedback, I truly value it.  I think we're both on the same page for many of these points.

> > we can't promise to never break BC in future major version (whether that's a >=1.0 major version or an 0.x major version).
>
> Um... why not? Isn't that the whole point of using semver in the first place? If you have to break BC, then it's time for a major version bump; plain and simple.

Sorry, I didn't word that very well.  I meant to say that it's unsafe for libraries to require an unbounded range like `league/commonmark: >=0.18` because we can (and likely **will**) break BC in future major releases. For example, that constraint says the `markdown` module is compatible with ALL future versions, even 2.x, 7.x, 217.x, etc.  A better constraint would be something like `^0.18`, `^1.0`, etc. as it prohibits the next major version.

> It's a little telling that there have been 50+ releases and it's still using "initial development" versioning... clearly, it's not "initial" anymore especially considering that it's been going on for 5+ years. There really should have already been several [normal] major version bumps by now.

Tell me about it :roll_eyes: The biggest challenge is that the underlying CommonMark spec is still not stable - they're currently on version 0.29.  The target deadline for 1.0 came and went.  There are still some missing features and outstanding issues the spec needs to address - any of which can drastically change how things get parsed, and in turn, what our implementation looks like.  We wanted our 1.0 release to correspond with theirs but I don't think it's feasible to wait any longer.

Thankfully the recent spec versions haven't changed the fundamental parsing logic very much so it feels much more stable.  I'm therefore comfortable making our 1.0 release in the very near future even if the spec isn't there yet.

(And although we have had 50+ releases, only 19 were `0.x` versions with BC breaks - fewer than the spec and reference parsers)

> I think, though, one of the primary issues is how this project handles adding new features and then immediately removes the code it's intended to replace.
> 
> Take for example #357, the PR is essentially ripping out all the "inline processing" APIs and replacing it with a new "delimiter processing" API... in the same PR. There is absolutely no breathing room here. This is what constitutes a BC break and why it would require a new major bump.
> 
> Instead, this is where the "inline processing" code should just deprecated and the new feature is added in a minor release. Then all subsequent core code/extensions are updated in a similar fashion to use the newly added APIs. There's no need to have a major release each time something changes like this. There can be a little bit of overlap.

Although we're allowed to this in `0.x` versions, we have done exactly what you described in many cases - search the changelog for `Deprecated` and you'll see several examples.  We absolutely plan to use this deprecation process where needed in `1.x`.

PR #357 is a special case.  The inline processing was never a good implementation - it was really only used by our own internal delimiter processing.  Other developers were unable to implement their own delimiter-based inlines - things like strikethrough support which follow the same rules as emphasis.

So we basically had two options:

 1. Release `1.0.0` with the bad, almost-useless implementation (and immediately deprecate it)
 2. Rip the bandage off now and have the proper implementation in `1.0.0` that we can support during the lifetime of that `1.x` branch

I opted for the second option.  Yes, it's more painful now, but it provides the implementation developers actually want and need.  And like you said, "when it's ready, whatever the next major version is... it bumps up to in that".  The next major version will either be `0.20` (the last of the `0.x` series) or `1.0` (my personal preference).  So we want to definitely have this in place for that version.

> As it stands now, it'll likely just be used to determine the current version installed more than anything. As time goes on and new features/settings are added, then I suspect it will be used more and more (e.g. 1.1.0 adds a new setting, then 1.2.0 adds a new setting and we have to determine what to show in the UI).

Thank you for that explanation!  I knew the constant was more efficient, but I was curious how/where/why knowing that version was being used.  This answers my question.  I'll un-deprecate the constant and keep it around :)

> I think getting out of the "initial development" versioning is the most important step forward.

Agreed!

> I think the two issues mentioned (#357) and (#232) are really not hard blockers for a 1.0.0 release.

Implementing these requires a major version bump.  We already have a working implementation for one of them (#357) so I'd rather get that into `1.0` so we have the _right_ implementation for our `1.0.0` release and can properly support that for a longer period of time.

I agree on #232 especially since what we have technically works fine and we don't have a working implementation for this change right now - let's save that for `2.0.0`

> I think that new features that replace the functionality of existing code should instead deprecated existing code rather than remove it entirely, thus allowing for more minor releases opposed to only major ones.

Agreed, especially with regards to `1.0.0` and onwards! But we need to get there first - and this should be the last time we skip the deprecation when going to the next major version.

> I think the version constant is still needed, regardless of how I'm using it... there may be reasons why other people are using it; it's just necessary. Perhaps some commenting needs to be added around why it's necessary (extracted from some of my reasons in #314).

Sounds good to me!

**Comment by glensc** [comment]
if it helps, I use two scripts to maintain `src/AppInfo::VERSION` constant:
- https://github.com/eventum/eventum/blob/v3.6.6/bin/releng/create-release.sh
- https://github.com/eventum/eventum/blob/v3.6.6/bin/releng/bump.sh

actually, it's a bit complicated, version for release is updated during tarball creation:
- https://github.com/eventum/eventum/blob/v3.6.6/bin/ci/release.sh#L111-L121

**Comment by colinodell** [comment]
Constant has been un-deprecated via d37c6d6d3bba5a1e69af376956283f7b00149766

**Comment by colinodell** [comment]
Our checklist has been completed so I'm going to close this issue :)

Just making a few last minute adjustments (see #367) so we can have a beta pre-release, get final feedback, and release a stable 1.0.0 version soon!
