### ISSUE TITLE
Fix responsive styles on documentation homepage

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#725]
When resizing the browser width on https://commonmark.thephpleague.com/, the `<h1>league/commonmark</h1>` heading is sometimes too wide and thus adds a scrollbar to the bottom:

![Peek 2021-10-02 12-15](https://user-images.githubusercontent.com/202034/135724447-9ed20731-6c8a-4599-b212-b41fcb71a5a4.gif)

Ideally, that `<h1>` should shrink in size so that no horizontal scroll bar appears on the bottom.

To complete this task, you will likely need:

- [ ] Knowledge about creating responsive CSS (`@media screen and (min-width:700px) { ... }`)
- [ ] Jekyll [installed locally](https://jekyllrb.com/docs/installation/) or the knowledge of how to run it via Docker

**Task List:**

- [ ] Fork and clone this project
- [ ] Update the CSS in `docs/homepage.css` to fix the issue
- [ ] Run `bundle exec jekyll serve` from within `./docs` to rebuild the docs and test your changes
- [ ] Push your changes to your fork
- [ ] Open a new PR with those changes

Thanks, and **Happy Hacktoberfest!**

**Comment by joelmheim** [comment]
I can take a stab at this one too. Have an idea on using viewport relative font-size.

**Comment by colinodell** [comment]
Awesome! It's all yours :)
