### ISSUE TITLE
Remove 0.19 docs

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#726]
The 0.x versions of this library are very old and no longer maintained.  I would therefore like to completely remove the 0.19 docs from the documentation site so that we don't have to maintain those pages anymore.

**Task List:**

- [ ] Fork and clone this repository
- [ ] Ensure you are on the `main` branch
- [ ] Completely remove the `docs/0.19` folder
- [ ] Remove lines 222-243 and 253 from `docs/_data/menu.yml`
- [ ] Remove lines 24-25 from `docs/_data/project.yml`
- [ ] Optional: Build the site with [Jekyll](https://jekyllrb.com/) locally to test your changes
- [ ] Commit and push your changes
- [ ] Open a new PR on this project that targets the `main` branch

Thanks, and **Happy Hacktoberfest!**

**Comment by joelmheim** [comment]
I'm on this. Will start immediately and make a PR within a few hours.
